version: "3.8"
services:

  fluentd:
    container_name: fluentd
    user: root
    build: ./fluentd/
    links:
      - "elasticsearch"
    volumes:
      - /var/lib/docker/containers:/fluentd/log/containers
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./logs:/output/
    ports: 
      - 9880:9880
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - "discovery.type=single-node"
    #volumes:
      #- ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - "9200"
    ports:
      - "9200:9200"

  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - 3000:3000


