version: "3.8"
services:
  fluentd:
    container_name: fluentd
    user: root
    image: fluentd
    volumes: 
    - /var/lib/docker/containers:/fluentd/log/containers
    - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
    - ./logs:/output/

